import { Page } from '@playwright/test';

export function healthLocator(page: Page) {
  return {
    selectFamilyMembers : page.getByText('+ Add members'),
    selectMemberCovered :page.getByText('Select members covered'),
    spouseAdd:page.locator('div').filter({ hasText: /^SpouseAdd$/ }).getByRole('button'),
    childAdd: page.locator('div').filter({ hasText: /^ChildAdd$/ }).getByRole('button'),
    multiChild:page.locator('div').filter({ hasText: /^ChildAdd$/ }).getByRole('button'),
    plusBtn:page.getByRole('button', { name: 'plus' }),
    parentAdd:page.locator('div').filter({ hasText: /^ParentAdd$/ }).getByRole('button'),
    multiParent : page.getByRole('button', { name: 'plus' }).nth(1),
    parentInLawAdd:page.getByRole('button', { name: 'Add' }),
    multiParentInLaw: page.getByRole('button', { name: 'plus' }).nth(2),
    maxAge:page.locator('div').filter({ hasText: /^SelfSpouse*/ }).getByRole('spinbutton'),
    maxAgeParent: page.getByRole('spinbutton').nth(1),
    maxAgeParentInLaw:page.getByRole('spinbutton').nth(2),
    continueBtn :page.getByRole('button',{ name: 'Continue' }),
    pincodeText:page.locator('div').filter({ hasText: /^Your pincode*/ }).getByRole('spinbutton').nth(0),
    mobileText: page.locator('div').filter({ hasText: /^Your pincode*/ }).getByRole('spinbutton').nth(1),
    proceedWithAckoPlatniumBtn: page.getByRole('button',{ name: 'Proceed with ACKO Platinum' }),
    mandatoryTest:page.getByRole('button',{ name: 'I am okay with mandatory tests' }),
    proceedBtn:page.getByRole('button',{ name: 'Proceed' }),
    viewPlanBtn:page.getByRole('button',{ name: 'View plan' }),
    seeYourPlanBtn:page.getByRole('button',{ name: 'See your plans' }),
    proceedWithAckoStandard:page.getByRole('button',{ name: 'Proceed with ACKO Standard' }),
    getOTP:page.getByRole('button',{ name: 'Get OTP' }),
    enterVerificationCode :page.getByText('Enter verification code'),
    otpFirstCol: page.getByPlaceholder('●').first(),
    otpSecondCol:page.getByPlaceholder('●').nth(1),
    otpThirdCol:page.getByPlaceholder('●').nth(2),
    otpFourCol :page.getByPlaceholder('●').nth(3),
    almostThereText:page.getByText('Almost there!'),
    memberDetailsText: page.getByText('Member Details'),
    mySelfName:page.getByRole('textbox').first(),
    dateSelector:page.getByRole('textbox').nth(1),
    yearSelector:page.getByRole('button', { name: 'Open Year Selector' }),
    yearChoose:page.getByRole('button', { name: '1996' }),
    monthSelector:page.getByRole('button', { name: 'Open Month Selector' }),
    monthChoose :page.getByRole('button', { name: 'May' }),
    exactDate:page.getByLabel('Saturday, 4 May'),
    genderBtn:page.locator('.sc-8183604c-0').first(),
    femaleBtn:page.getByRole('button', { name: 'Female' }),
    selfCheck:page.getByRole('spinbutton'),
    selfCheckTwo: page.locator('div:nth-child(3) > div > .sc-a80624f1-0 > .sc-a80624f1-1 > .sc-a80624f1-3'),
    panCardTextBox:page.locator('div:nth-child(3) > div > .sc-32538024-0 > .sc-32538024-1 > .sc-32538024-3'),
    emailTextBox :page.locator('input[type="email"]'),
    spouseName:page.locator('(//*[text()="Spouse"] //following::input)[1]'),
    spouseDateSelctor:page.getByRole('textbox').nth(5),
    spouseSelect:page.locator('.sc-8183604c-0').nth(1),
    maleGender:page.getByRole('button', { name: 'Male', exact: true }),
    childName:page.locator('(//*[text()="Child"] //following::input)[1]'),
    childCheck:page.getByRole('textbox').nth(7),
    parentName:page.locator('(//*[text()="Parent 1"] //following::input)[1]'),
    parentChoose:page.getByRole('textbox').nth(9),
    femaleGender:page.getByRole('button', { name: 'Female', exact: true }),
    parentTwo:page.locator('(//*[text()="Parent 2"] //following::input)[1]'),
    parentchoose:page.getByRole('textbox').nth(11),
    parentInLawName:page.locator('(//*[text()="Parent-in-Law 1"] //following::input)[1]'),
    parentInLawChoose :page.getByRole('textbox').nth(13),
    parentInLawTwoName:page.locator('(//*[text()="Parent-in-Law 2"] //following::input)[1]'),
    parentInLawTwoChoose :page.getByRole('textbox').nth(15),
    continueSecondBtn :page.getByRole('button', { name: 'Continue' }).nth(1),
    monthlyPayment:page.getByText('Monthly', { exact: true }),
    payNowBtn:page.getByRole('button', { name: 'Pay now' }),
    paySub:page.locator('#type'),
    juspayMock:page.getByRole('heading', { name: 'Juspay Mock' }),
    jusupayText:page.getByText('This is a mock page for Juspay payment'),
    successBtn:page.getByRole('button',{ name: 'Success' }),
    verifyKyc:page.getByRole('button', { name: 'Verify KYC' }),
    aspPolicy:page.locator('span').filter({ hasText: 'Arogya Sanjeevani Policy' }),
    standardPolicy:page.locator('span').filter({ hasText: 'ACKO Standard Health Plan' }),
    policyExpirationDate:page.getByLabel('Current policy expiration date'),
    submitBtn:page.getByRole('button', { name: 'Submit' }),
    proceedToPaymentBtn:page.getByRole('button', { name: 'Proceed to payment' }),
    disclamirText:page.getByText('Ensure your answers are'),
    smokeTabacooQs:page.getByText('Has anyone covered in this plan smoked or chewed tobacco in the past year?'),
    noAnswer:page.getByText('No'),
    alchoalQs:page.getByText('Has anyone covered in this plan consumed alcohol in the past year?'),
    diagonsedMedicalCondition:page.getByText('Has anyone in this plan been diagnosed with a medical condition?'),
    noMedicalConditionOption:page.getByText('No medical conditions'),
    prescribedText:page.getByText('Did anyone in this plan take any prescribed medicines in the past week?'),
    experincingSymptoms:page.getByText('Is anyone in this plan currently experiencing any of the following symptoms?'),
    noSymptomsOption:page.locator('div').filter({ hasText: /^No symptoms$/ }).first(),
    suregeryText:page.getByText('Did anyone in this plan undergo surgery or get hospitalised in the past 10 years?'),
    noAns:page.getByText('No', { exact: true }),
    pregQues:page.getByText('Are you or your spouse pregnant?'),
    ongoingHealthIssue:page.getByText('Does anyone in this plan have any other ongoing health issues or symptoms for which you are planning a doctor visit?'),
    confirmationQuestion:page.getByText('I confirm that I have answered all the medical questions truthfully and accurately.'),
    iConirmBtn:page.getByRole('button', { name: 'I confirm' }),
    btnText: page.locator('[id="__next"]'),
    spouseSEM:page.getByText('Spouse', { exact: true }).nth(1),
    childSEM:page.getByText('Child', { exact: true }).nth(1),
    childSEMtwo:page.getByRole('img', { name: 'family-logo' }).nth(2),
    multiChildSEM:page.getByRole('button', { name: 'plus' }),
    parentSEM:page.getByText('Parent', { exact: true }).nth(1),
    multiParentSEM :page.getByRole('button', { name: 'plus' }).nth(1),
    parentInLawSEM:page.getByText('Parent In-Law').nth(1),
    parentInLawTwo:page.getByRole('button', { name: 'plus' }).nth(2),
    maxAgeSEM:page.locator('div').filter({ hasText: /^Eldest member \(self, spouse\)$/ }).getByRole('spinbutton'),
    topuPSelector:page.locator('div').filter({ hasText: /^Select existing cover \(deductible\)$/ }).first(),
    maxAgeParentSEM:page.locator('div').filter({ hasText: /^Eldest parent$/ }).getByRole('spinbutton'),
    maxAgeParentInLawSEM:page.locator('div').filter({ hasText: /^Eldest parent-in-law$/ }).getByRole('spinbutton'),
    mobileNumberSEM :page.locator('//div[text()="+91"]//following::input').first(),
    pincodeSEM:page.locator('//div[text()="+91"]//following::input').nth(1),
    checkPriceBtn:page.getByRole('button', { name: 'Check Your Price' }),
    checkPriceBtnSEO :page.getByRole('button', { name: 'Check prices' }),
    loginButton: page.getByRole('button', { name: 'Login' }),
    loginTextBox : page.getByRole('spinbutton'),
    loginOTPbtn: page.getByRole('button', { name: 'Log in' }),
    verificationText: page.getByText('Enter verification code'),
    gmcClick: page.locator('div').filter({ hasText: /^Health$/ }).nth(1),
    buyaNewPlan: page.getByText('Buy a new plan'),
    pincodeGMC: page.getByRole('spinbutton').first(),
    mobileNumberSEO:page.getByRole('spinbutton').nth(1),
    pincodeSEO:page.getByRole('spinbutton').nth(2),
    portingJourney: page.getByText('Port to ACKO Health'),
    portingLessThantwoMonths: page.locator('div').filter({ hasText: /^Less than 2 months$/ }),
    topupJourney:page.getByText('Top-up existing coverage'),
    seeAllAckoHealthPlan:page.getByRole('button', { name: 'See all ACKO health plans ->' }),
    standardPlan:page.locator('label').filter({ hasText: 'ACKO Standard Health' }).locator('div').first(),
    selectAndCustomizeBtn:page.getByRole('button', { name: 'Select and customize' }),
    arogyaSanjevini:page.locator('label').filter({ hasText: 'Arogya SanjeevaniCovers you' }).locator('div').first(),
    platniumPlan:page.locator('label').filter({ hasText: 'ACKO Platinum Health' }).locator('div').first(),
    spouseSelectSEM:page.getByRole('img', { name: 'family-logo' }).nth(1),
    childSelectSEM :page.getByRole('img', { name: 'family-logo' }).nth(2),
    selectDeductible:page.locator('div').filter({ hasText: /^Select existing cover \(deductible\)$/ }).nth(3),
    viewBtn:page.getByRole('button', { name: 'View' }),
    revisedPremiumtText:page.getByText('We have revised your premium'),
    reviewYourPlanBtn:page.getByRole('button', { name: 'Review your plan' }),
    priceBreakup:page.getByText('See detailed price breakup'),
    okayBtn:page.getByRole('button', { name: 'Okay' }),
    acceptPayBtn:page.getByRole('button', { name: 'Accept & pay' }),
    dateofBirthSelfSelector :page.getByText('DOB (dd/mm/yyyy)//').first(),
    dayselfSelector: page.locator('#Self-dob-day'),
    monthselfSelector:page.locator('#Self-dob-month'),
    yearSelfSelector:page.locator('#Self-dob-year'),
    dateofBirthspouseSelector:page.getByText('DOB (dd/mm/yyyy)//').nth(1),
    daySpouseSelector:page.locator('#Spouse-dob-day'),
    monthSpouseSelector:page.locator('#Spouse-dob-month'),
    yearSpouseSelector:page.locator('#Spouse-dob-year'),
    dateofBirthSelectorChild:page.getByText('DOB (dd/mm/yyyy)//').nth(2),
    dayChildSelector: page.locator('#Child-dob-day'),
    monthChildSelector:page.locator('#Child-dob-month'),
    yearChildSelector:page.locator('#Child-dob-year'),
    martialStatusCTA:page.locator('div').filter({ hasText: /^Your marital status$/ }).nth(3),
    singleOption: page.getByRole('button', { name: 'Single' }),
    textGenericOption: page.locator('[id="__next"]'),
    platniumJourney: page.locator('div').filter({ hasText: /^ACKO Platinum$/ }).first(),
    platniumProceedCTA:  page.getByRole('button', { name: 'Proceed with ACKO Platinum' }),
    





  

    
  }
}